version: '3.1'

services:

    inert-bot:

        container_name: inert-bot
        hostname: inert-bot
        restart: unless-stopped

        build: ./
        image: blots/inert-bot

        env_file: 
            - .env

